# Generated by Django 3.0.14 on 2021-07-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
