# Generated by Django 3.0.14 on 2021-07-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20210716_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='about',
            field=models.CharField(blank=True, max_length=255, verbose_name='circle description'),
        ),
    ]
